apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              value: "password"
            - name: "MYSQL_USER"
              value: "soauser"
            - name: "MYSQL_PASSWORD"
              value: "soauser"
            - name: "MYSQL_DATABASE"
              value: "soadb"
            - name: "MYSQL_ROOT_HOST"
              value: "%"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
