apiVersion: v1
kind: Service
metadata:
  name: soacilapp
  namespace: soacil
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
      name: auth
    # - port: 9091
    #   targetPort: 9091
    #   name: notif
    # - port: 9092
    #   targetPort: 9092
    #   name: post
    # - port: 9093
    #   targetPort: 9093
    #   name: user
    # - port: 5672
    #   targetPort: 5672
    #   name: rabbit
  selector:
    app: soacilapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soacilapp
  namespace: soacil
spec:
  replicas: 2
  selector:
    matchLabels:
      app: soacilapp
  template:
    metadata:
      labels:
        app: soacilapp
    spec:
      containers:
        - name: auth-service
          image: zedd08/soacil-auth-service
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 9090
        # - name: notif-service
        #   image: zedd08/soacil-notif-service
        #   resources:
        #     limits:
        #       memory: "512Mi"
        #       cpu: "500m"
        #   ports:
        #     - containerPort: 9091
        # - name: post-service
        #   image: zedd08/soacil-post-service
        #   resources:
        #     limits:
        #       memory: "512Mi"
        #       cpu: "500m"
        #   ports:
        #     - containerPort: 9092
        # - name: user-service
        #   image: zedd08/soacil-user-service
        #   resources:
        #     limits:
        #       memory: "512Mi"
        #       cpu: "500m"
        #   ports:
        #     - containerPort: 9093
        # - name: rabbitmq
        #   image: rabbitmq:latest
        #   resources:
        #     limits:
        #       memory: "512Mi"
        #       cpu: "500m"
        #   ports:
        #     - containerPort: 5672
