apiVersion: v1
kind: Service
metadata:
  name: rabbit
  namespace: soacil
spec:
  type: LoadBalancer
  ports:
    - port: 5672
      targetPort: 5672
      name: rabbit
  selector:
    app: rabbit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  namespace: soacil
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5672
